// === NEW CAM TOPIC METAS (add to TOPIC_META array) ===
  {name:"Du lịch & Khám phá (CAM)",emoji:"🗺️"},
  {name:"Khoa học & Môi trường (CAM)",emoji:"🔬"},
  {name:"Xã hội & Kinh tế (CAM)",emoji:"🏛️"},
  {name:"Học thuật & Nghiên cứu (CAM)",emoji:"📖"},
  {name:"Công nghiệp & Vật liệu (CAM)",emoji:"🏗️"},
  {name:"Kỹ năng & Giao tiếp (CAM)",emoji:"🗣️"},
  {name:"Sức khỏe & Đời sống (CAM)",emoji:"🏥"},
  {name:"Lịch sử & Khảo cổ (CAM)",emoji:"🏺"},

// === NEW CAM RAW DATA (add to RAW array) ===
// Du lịch & Khám phá (CAM)
`century|thế kỷ,transport|vận chuyển/giao thông,director|giám đốc,officer|sĩ quan/nhân viên,official|chính thức/quan chức,agent|đại lý/nhân viên,member|thành viên,crew|thủy thủ đoàn/phi hành đoàn,captain|thuyền trưởng/đội trưởng,guide|hướng dẫn viên,brochure|tờ rơi quảng cáo,continent|lục địa,desert|sa mạc,ground|mặt đất,entrance|lối vào,path|con đường/lối đi,track|đường mòn/theo dõi,trail|đường mòn,bay|vịnh,lodge|nhà nghỉ,campsite|bãi cắm trại,tent|lều,shelter|nơi trú ẩn,castle|lâu đài,fortress|pháo đài,palace|cung điện,monument|đài tưởng niệm,architecture|kiến trúc,ancient|cổ đại,medieval|trung cổ,historic|lịch sử,historical|thuộc lịch sử,famous|nổi tiếng,renowned|nổi tiếng,original|nguyên bản/gốc,originally|ban đầu,accommodation|chỗ ở,destination|điểm đến,arrival|sự đến nơi,holiday|kỳ nghỉ,outdoor|ngoài trời,interior|nội thất/bên trong,somewhere|đâu đó,booking|đặt chỗ,rental|cho thuê,fee|phí,membership|tư cách thành viên,club|câu lạc bộ,award|giải thưởng,competition|cuộc thi,exhibition|triển lãm,gallery|phòng trưng bày,film|phim`,
// Khoa học & Môi trường (CAM)
`species|loài,habitat|môi trường sống,vegetation|thảm thực vật,wildlife|động vật hoang dã,predator|động vật ăn thịt,prey|con mồi,breeding|sinh sản,native|bản địa,giant|khổng lồ,cattle|gia súc,conservation|bảo tồn,endangered|bị đe dọa tuyệt chủng,extinct|tuyệt chủng,survive|sống sót,adapt|thích nghi,evolution|tiến hóa,genetic|di truyền,gene|gen,cell|tế bào,organism|sinh vật,climate|khí hậu,temperature|nhiệt độ,drought|hạn hán,flood|lũ lụt,pollution|ô nhiễm,emission|khí thải,renewable|tái tạo được,recycle|tái chế,recycling|việc tái chế,waste|chất thải/lãng phí,ecosystem|hệ sinh thái,environmental|thuộc môi trường,global|toàn cầu,destruction|sự tàn phá,disease|bệnh,mortality|tỷ lệ tử vong,sanitation|vệ sinh,flow|dòng chảy,terrain|địa hình,volcano|núi lửa,mineral|khoáng sản,scientific|khoa học`,
// Xã hội & Kinh tế (CAM)
`society|xã hội,community|cộng đồng,government|chính phủ,council|hội đồng,economy|nền kinh tế,economic|kinh tế,industry|công nghiệp,revolution|cuộc cách mạng,development|sự phát triển,growth|sự tăng trưởng,trade|thương mại,export|xuất khẩu,import|nhập khẩu,investment|đầu tư,profit|lợi nhuận,income|thu nhập,budget|ngân sách,poverty|nghèo đói,wealth|sự giàu có,wealthy|giàu có,employment|việc làm,unemployment|thất nghiệp,employer|người sử dụng lao động,training|đào tạo,policy|chính sách,reform|cải cách,impact|tác động,influence|ảnh hưởng,survey|khảo sát,statistics|thống kê,increase|tăng,decrease|giảm,decline|suy giảm,significant|đáng kể,citizen|công dân,cultural|văn hóa,tradition|truyền thống,traditional|truyền thống,progress|tiến bộ,challenge|thách thức,crisis|khủng hoảng,crime|tội phạm,theft|trộm cắp,charity|từ thiện,volunteer|tình nguyện viên,contribution|đóng góp,cooperation|hợp tác,demand|nhu cầu,labour|lao động,agriculture|nông nghiệp,manufacturing|sản xuất,production|sản xuất,commercial|thương mại,domestic|trong nước,expansion|mở rộng,social|xã hội,national|quốc gia,international|quốc tế,regional|khu vực,war|chiến tranh,payment|thanh toán,scheme|kế hoạch/đề án`,
// Học thuật & Nghiên cứu (CAM)
`intelligence|trí thông minh,theory|lý thuyết,cognitive|nhận thức,psychology|tâm lý học,behavior|hành vi,mental|tinh thần,ability|khả năng,capable|có khả năng,potential|tiềm năng,intelligent|thông minh,identify|nhận dạng,recognize|nhận ra,interpret|giải thích,evaluate|đánh giá,assess|đánh giá,assessment|sự đánh giá,compare|so sánh,contrast|tương phản,similar|tương tự,unique|độc đáo,factor|yếu tố,aspect|khía cạnh,perspective|góc nhìn,approach|cách tiếp cận,concept|khái niệm,principle|nguyên tắc,hypothesis|giả thuyết,phenomenon|hiện tượng,relevant|liên quan,context|bối cảnh,indicate|chỉ ra,demonstrate|chứng minh,suggest|gợi ý,argue|lập luận,claim|tuyên bố,support|ủng hộ,conclude|kết luận,define|định nghĩa,complex|phức tạp,fundamental|cơ bản,essential|cần thiết,research|nghiên cứu,experiment|thí nghiệm,laboratory|phòng thí nghiệm,observe|quan sát,discover|khám phá,evidence|bằng chứng,analysis|phân tích,conclusion|kết luận,result|kết quả,process|quá trình,method|phương pháp,sample|mẫu,measure|đo lường,accurate|chính xác,precise|chính xác,reliable|đáng tin cậy`,
// Công nghiệp & Vật liệu (CAM)
`glass|thủy tinh,stone|đá,copper|đồng,steel|thép,iron|sắt,metal|kim loại,wood|gỗ,concrete|bê tông,brick|gạch,material|vật liệu,substance|chất,chemical|hóa chất,liquid|chất lỏng,solid|chất rắn,fuel|nhiên liệu,energy|năng lượng,engine|động cơ,motor|động cơ,machine|máy móc,factory|nhà máy,manufacture|sản xuất,product|sản phẩm,design|thiết kế,designer|nhà thiết kế,construction|xây dựng,structure|cấu trúc,foundation|nền móng,layer|lớp,surface|bề mặt,pipe|ống,wire|dây,tool|dụng cụ,device|thiết bị,equipment|thiết bị,shape|tạo hình/hình dạng,mold|khuôn,repair|sửa chữa,maintain|bảo trì,inspect|kiểm tra,standard|tiêu chuẩn,raw|thô/nguyên liệu,cargo|hàng hóa,painting|bức tranh/sơn,restoration|sự phục hồi,restore|phục hồi,invention|phát minh`,
// Kỹ năng & Giao tiếp (CAM)
`provide|cung cấp,organize|tổ chức,arrange|sắp xếp,continue|tiếp tục,allow|cho phép,prevent|ngăn chặn,avoid|tránh,encourage|khuyến khích,focus|tập trung,improve|cải thiện,gain|đạt được,achieve|đạt được,determine|xác định,explain|giải thích,describe|mô tả,discuss|thảo luận,separate|tách biệt,involve|liên quan/bao gồm,operate|vận hành,function|chức năng,select|chọn lọc,locate|xác định vị trí,predict|dự đoán,prepare|chuẩn bị,replace|thay thế,remove|loại bỏ,propose|đề xuất,declare|tuyên bố,ensure|đảm bảo,employ|tuyển dụng/sử dụng,serve|phục vụ,benefit|lợi ích,advantage|lợi thế,value|giá trị,limit|giới hạn,range|phạm vi,amount|số lượng,rate|tỷ lệ,level|mức độ,condition|điều kiện,opportunity|cơ hội,purpose|mục đích,reason|lý do,solution|giải pháp,problem|vấn đề,safety|an toàn,personal|cá nhân,individual|cá nhân/riêng,general|chung/tổng quát,basic|cơ bản,specific|cụ thể,recent|gần đây,recently|gần đây,particularly|đặc biệt,especially|đặc biệt là,directly|trực tiếp,clearly|rõ ràng,quickly|nhanh chóng,slightly|hơi/một chút,relatively|tương đối,fully|hoàn toàn,highly|rất/cao,equally|bằng nhau,apparently|rõ ràng là`,
// Sức khỏe & Đời sống (CAM)
`fitness|thể lực/sức khỏe,improvement|sự cải thiện,leisure|giải trí/thời gian rảnh,supervisor|người giám sát,trainer|huấn luyện viên,professor|giáo sư,birth|sự sinh ra,infant|trẻ sơ sinh,human|con người,harm|gây hại,suffer|chịu đựng,recover|hồi phục,treat|điều trị,recommend|khuyến nghị,sufficient|đủ,necessary|cần thiết,suitable|phù hợp,available|có sẵn,useful|hữu ích,interested|quan tâm,interesting|thú vị,pleasant|dễ chịu,pleased|hài lòng,excellent|xuất sắc,lovely|đáng yêu,unusual|bất thường,widespread|lan rộng,ambitious|tham vọng,huge|khổng lồ,popular|phổ biến,double|gấp đôi,whole|toàn bộ,major|lớn/quan trọng,effective|hiệu quả,successful|thành công,likely|có khả năng,elite|tinh hoa,peak|đỉnh cao,concern|lo ngại,term|thuật ngữ/kỳ hạn,role|vai trò,trust|tin tưởng,damage|thiệt hại,deal|thỏa thuận/giải quyết,importance|tầm quan trọng,wonder|thắc mắc/kỳ diệu,notice|chú ý/thông báo,content|nội dung/hài lòng,sense|giác quan/ý nghĩa`,
// Lịch sử & Khảo cổ (CAM)
`archaeological|khảo cổ học,dramatic|kịch tính,era|kỷ nguyên,significance|ý nghĩa/tầm quan trọng,access|sự tiếp cận,commission|ủy ban,land|đất đai,settler|người định cư,establishment|sự thành lập,programme|chương trình,extent|mức độ,report|báo cáo,volume|khối lượng/tập sách,period|giai đoạn,cycle|chu kỳ,application|ứng dụng/đơn xin,operation|hoạt động,position|vị trí,location|địa điểm,state|trạng thái/bang,system|hệ thống,technique|kỹ thuật,technology|công nghệ,queen|nữ hoàng,king|vua,hall|hội trường,carved|được chạm khắc,decorative|trang trí,sculpture|tác phẩm điêu khắc,rise|sự trỗi dậy/tăng,sudden|đột ngột,length|chiều dài,absence|sự vắng mặ,distinct|khác biệt,ambitious|tham vọng,unprecedented|chưa từng có,barren|cằn cỗi,uneven|không đều`,
