// IELTS Vocabulary Data - Band 4.0 & Below (~1000 words)
// Format: "word|meaning" separated by commas, parsed at runtime
const TOPIC_META = [
  {name:"Gia đình & Quan hệ",emoji:"👨‍👩‍👧‍👦"},
  {name:"Thức ăn & Đồ uống",emoji:"🍽️"},
  {name:"Sinh hoạt hàng ngày",emoji:"🌅"},
  {name:"Nhà cửa",emoji:"🏠"},
  {name:"Trường học & Giáo dục",emoji:"🎓"},
  {name:"Công việc & Nghề nghiệp",emoji:"💼"},
  {name:"Sức khỏe & Cơ thể",emoji:"🏥"},
  {name:"Mua sắm & Tiền bạc",emoji:"🛒"},
  {name:"Du lịch & Giao thông",emoji:"✈️"},
  {name:"Thời tiết & Mùa",emoji:"🌤️"},
  {name:"Thể thao & Sở thích",emoji:"⚽"},
  {name:"Động vật & Thiên nhiên",emoji:"🌿"},
  {name:"Quần áo & Ngoại hình",emoji:"👗"},
  {name:"Số đếm & Thời gian",emoji:"⏰"},
  {name:"Màu sắc & Hình dạng",emoji:"🎨"},
  {name:"Cảm xúc & Tính cách",emoji:"😊"},
  {name:"Thành phố & Địa điểm",emoji:"🏙️"},
  {name:"Công nghệ",emoji:"💻"},
  {name:"Động từ thông dụng",emoji:"🔄"},
  {name:"Tính từ & Trạng từ",emoji:"📝"},
  {name:"Du lịch & Khám phá (CAM)",emoji:"🗺️"},
  {name:"Khoa học & Môi trường (CAM)",emoji:"🔬"},
  {name:"Xã hội & Kinh tế (CAM)",emoji:"🏛️"},
  {name:"Học thuật & Nghiên cứu (CAM)",emoji:"📖"},
  {name:"Công nghiệp & Vật liệu (CAM)",emoji:"🏗️"},
  {name:"Kỹ năng & Giao tiếp (CAM)",emoji:"🗣️"},
  {name:"Sức khỏe & Đời sống (CAM)",emoji:"🏥"},
  {name:"Lịch sử & Khảo cổ (CAM)",emoji:"🏺"},
  {name:"Giao thông & Đô thị (CAM 17)",emoji:"🚇"},
  {name:"Khoa học & Tự nhiên (CAM 17)",emoji:"🦇"},
  {name:"Nông nghiệp & Đô thị xanh (CAM 18)",emoji:"🌱"},
  {name:"Công nghệ & Khám phá (CAM 18)",emoji:"🚀"}
];

const RAW = [
// 0: Family
`mother|mẹ,father|bố,brother|anh/em trai,sister|chị/em gái,son|con trai,daughter|con gái,husband|chồng,wife|vợ,baby|em bé,child|đứa trẻ,children|trẻ em,parent|cha mẹ,grandma|bà,grandpa|ông,uncle|chú/bác,aunt|cô/dì,cousin|anh chị em họ,nephew|cháu trai,niece|cháu gái,family|gia đình,friend|bạn,neighbor|hàng xóm,couple|cặp đôi,wedding|đám cưới,marry|kết hôn,love|yêu,care|quan tâm,help|giúp đỡ,together|cùng nhau,alone|một mình,young|trẻ,old|già,twin|sinh đôi,born|được sinh ra,grow|lớn lên,name|tên,age|tuổi,man|đàn ông,woman|phụ nữ,boy|con trai,girl|con gái,people|người/mọi người,person|người,gentleman|quý ông,lady|quý bà,kid|đứa trẻ,adult|người lớn,relative|họ hàng,relationship|mối quan hệ,single|độc thân,divorce|ly dị`,
// 1: Food
`food|thức ăn,rice|gạo/cơm,bread|bánh mì,meat|thịt,chicken|thịt gà,fish|cá,egg|trứng,milk|sữa,water|nước,juice|nước ép,tea|trà,coffee|cà phê,sugar|đường,salt|muối,soup|súp,noodle|mì,fruit|trái cây,apple|táo,banana|chuối,orange|cam,vegetable|rau,potato|khoai tây,tomato|cà chua,onion|hành,carrot|cà rốt,cake|bánh ngọt,cheese|phô mai,butter|bơ,oil|dầu,pepper|tiêu,cook|nấu ăn,eat|ăn,drink|uống,hungry|đói,thirsty|khát,breakfast|bữa sáng,lunch|bữa trưa,dinner|bữa tối,meal|bữa ăn,dish|món ăn,taste|nếm/vị,sweet|ngọt,sour|chua,spicy|cay,bitter|đắng,fresh|tươi,delicious|ngon,menu|thực đơn,restaurant|nhà hàng,kitchen|nhà bếp,plate|đĩa,cup|cốc/ly`,
// 2: Daily
`wake|thức dậy,sleep|ngủ,dream|mơ/giấc mơ,rest|nghỉ ngơi,shower|tắm,brush|chải,wash|rửa/giặt,dress|mặc quần áo,breakfast|ăn sáng,lunch|ăn trưa,dinner|ăn tối,work|làm việc,study|học,read|đọc,write|viết,drive|lái xe,walk|đi bộ,run|chạy,sit|ngồi,stand|đứng,clean|dọn dẹp,cook|nấu ăn,watch|xem,listen|nghe,talk|nói chuyện,call|gọi điện,meet|gặp,visit|thăm,play|chơi,exercise|tập thể dục,shop|mua sắm,relax|thư giãn,morning|buổi sáng,afternoon|buổi chiều,evening|buổi tối,night|ban đêm,today|hôm nay,tomorrow|ngày mai,yesterday|hôm qua,always|luôn luôn,never|không bao giờ,sometimes|thỉnh thoảng,usually|thường,often|thường xuyên,early|sớm,late|muộn,ready|sẵn sàng,busy|bận,free|rảnh,tired|mệt,finish|hoàn thành`,
// 3: House
`house|nhà,home|nhà/gia đình,room|phòng,bedroom|phòng ngủ,bathroom|phòng tắm,kitchen|nhà bếp,living room|phòng khách,garden|vườn,door|cửa,window|cửa sổ,wall|tường,floor|sàn nhà,roof|mái nhà,stairs|cầu thang,key|chìa khóa,lock|khóa,bed|giường,table|bàn,chair|ghế,sofa|ghế sofa,desk|bàn làm việc,lamp|đèn,light|đèn/ánh sáng,fan|quạt,mirror|gương,clock|đồng hồ,shelf|kệ,closet|tủ quần áo,fridge|tủ lạnh,oven|lò nướng,sink|bồn rửa,towel|khăn tắm,pillow|gối,blanket|chăn,curtain|rèm cửa,carpet|thảm,balcony|ban công,garage|nhà xe,fence|hàng rào,gate|cổng,apartment|căn hộ,building|tòa nhà,address|địa chỉ,move|chuyển nhà,rent|thuê,own|sở hữu,neighbor|hàng xóm,quiet|yên tĩnh,noisy|ồn ào,comfortable|thoải mái,clean|sạch`,
// 4: School
`school|trường học,class|lớp học,classroom|phòng học,teacher|giáo viên,student|học sinh,lesson|bài học,subject|môn học,math|toán,science|khoa học,English|tiếng Anh,history|lịch sử,art|mỹ thuật,music|âm nhạc,sport|thể thao,book|sách,notebook|vở,pen|bút,pencil|bút chì,eraser|cục tẩy,ruler|thước kẻ,bag|cặp sách,board|bảng,exam|bài thi,test|kiểm tra,homework|bài tập về nhà,question|câu hỏi,answer|câu trả lời,read|đọc,write|viết,count|đếm,learn|học,teach|dạy,study|ôn bài,pass|đậu,fail|trượt,grade|điểm,library|thư viện,uniform|đồng phục,break|giờ ra chơi,principal|hiệu trưởng,practice|luyện tập,understand|hiểu,remember|nhớ,forget|quên,difficult|khó,easy|dễ,smart|thông minh,knowledge|kiến thức,exercise|bài tập,dictionary|từ điển,page|trang`,
// 5: Work
`work|làm việc,job|công việc,office|văn phòng,company|công ty,boss|sếp,manager|quản lý,worker|công nhân,doctor|bác sĩ,nurse|y tá,teacher|giáo viên,driver|tài xế,farmer|nông dân,cook|đầu bếp,police|cảnh sát,soldier|lính,singer|ca sĩ,actor|diễn viên,lawyer|luật sư,engineer|kỹ sư,dentist|nha sĩ,pilot|phi công,sailor|thủy thủ,waiter|bồi bàn,cleaner|người dọn dẹp,builder|thợ xây,painter|thợ sơn,mechanic|thợ máy,barber|thợ cắt tóc,salary|lương,money|tiền,earn|kiếm tiền,pay|trả lương,hire|thuê,fire|sa thải,retire|nghỉ hưu,meeting|cuộc họp,project|dự án,skill|kỹ năng,experience|kinh nghiệm,apply|ứng tuyển,interview|phỏng vấn,team|đội nhóm,task|nhiệm vụ,deadline|hạn chót,busy|bận rộn,part-time|bán thời gian,full-time|toàn thời gian,colleague|đồng nghiệp,customer|khách hàng,business|kinh doanh,success|thành công`,
// 6: Health
`head|đầu,face|mặt,eye|mắt,ear|tai,nose|mũi,mouth|miệng,tooth|răng,hair|tóc,neck|cổ,shoulder|vai,arm|cánh tay,hand|bàn tay,finger|ngón tay,chest|ngực,stomach|bụng/dạ dày,back|lưng,leg|chân,knee|đầu gối,foot|bàn chân,toe|ngón chân,skin|da,blood|máu,heart|tim,bone|xương,muscle|cơ bắp,sick|ốm,pain|đau,fever|sốt,cold|cảm lạnh,cough|ho,headache|đau đầu,medicine|thuốc,hospital|bệnh viện,doctor|bác sĩ,health|sức khỏe,healthy|khỏe mạnh,exercise|tập thể dục,strong|khỏe/mạnh,weak|yếu,hurt|bị thương,rest|nghỉ ngơi,recover|hồi phục,diet|chế độ ăn,weight|cân nặng,tall|cao,short|thấp,fat|béo,thin|gầy,breathe|thở,allergy|dị ứng,dentist|nha sĩ,check-up|khám sức khỏe`,
// 7: Shopping
`shop|cửa hàng,store|cửa hàng,market|chợ,mall|trung tâm thương mại,buy|mua,sell|bán,pay|trả tiền,money|tiền,price|giá,cheap|rẻ,expensive|đắt,free|miễn phí,cost|chi phí,bill|hóa đơn,change|tiền thối,cash|tiền mặt,card|thẻ,wallet|ví,bag|túi,basket|giỏ,cart|xe đẩy,receipt|hóa đơn,discount|giảm giá,sale|khuyến mãi,try|thử,size|cỡ/kích thước,color|màu sắc,brand|thương hiệu,quality|chất lượng,choose|chọn,order|đặt hàng,deliver|giao hàng,return|trả lại,exchange|đổi,online|trực tuyến,gift|quà tặng,wrap|gói,spend|tiêu tiền,save|tiết kiệm,afford|đủ khả năng,borrow|mượn,lend|cho mượn,owe|nợ,bank|ngân hàng,account|tài khoản,coin|đồng xu,dollar|đô la,total|tổng cộng,tax|thuế,tip|tiền boa,customer|khách hàng,cashier|thu ngân`,
// 8: Travel
`travel|du lịch,trip|chuyến đi,vacation|kỳ nghỉ,visit|thăm quan,car|xe hơi,bus|xe buýt,train|tàu hỏa,plane|máy bay,bike|xe đạp,taxi|xe taxi,boat|thuyền,ship|tàu thủy,airport|sân bay,station|nhà ga,ticket|vé,passport|hộ chiếu,luggage|hành lý,bag|túi xách,map|bản đồ,hotel|khách sạn,room|phòng,book|đặt phòng,arrive|đến,leave|rời đi,depart|khởi hành,return|trở về,fly|bay,ride|đi (xe),drive|lái xe,walk|đi bộ,road|đường,street|đường phố,bridge|cầu,highway|đường cao tốc,traffic|giao thông,turn|rẽ,left|trái,right|phải,straight|thẳng,stop|dừng,park|đậu xe,gas|xăng,fast|nhanh,slow|chậm,far|xa,near|gần,tourist|du khách,guide|hướng dẫn viên,beach|bãi biển,mountain|núi,country|quốc gia,city|thành phố`,
// 9: Weather
`weather|thời tiết,sun|mặt trời,rain|mưa,snow|tuyết,wind|gió,cloud|mây,storm|bão,fog|sương mù,hot|nóng,cold|lạnh,warm|ấm,cool|mát,dry|khô,wet|ướt,sunny|nắng,rainy|mưa,cloudy|nhiều mây,windy|nhiều gió,snowy|có tuyết,foggy|sương mù,spring|mùa xuân,summer|mùa hè,autumn|mùa thu,winter|mùa đông,season|mùa,temperature|nhiệt độ,degree|độ,freeze|đóng băng,melt|tan chảy,flood|lũ lụt,thunder|sấm,lightning|sét,rainbow|cầu vồng,umbrella|ô/dù,coat|áo khoác,sky|bầu trời,star|ngôi sao,moon|mặt trăng,shine|tỏa sáng,dark|tối,bright|sáng,ice|băng,heat|sức nóng,climate|khí hậu,forecast|dự báo,nature|thiên nhiên,air|không khí,blow|thổi,clear|trong lành,humid|ẩm ướt,drought|hạn hán`,
// 10: Sports
`sport|thể thao,play|chơi,game|trò chơi,team|đội,win|thắng,lose|thua,draw|hòa,score|điểm số,goal|bàn thắng,ball|quả bóng,football|bóng đá,basketball|bóng rổ,tennis|quần vợt,swim|bơi,run|chạy,jump|nhảy,kick|đá,throw|ném,catch|bắt,hit|đánh,race|cuộc đua,match|trận đấu,player|cầu thủ,coach|huấn luyện viên,referee|trọng tài,stadium|sân vận động,pool|hồ bơi,gym|phòng tập,exercise|tập thể dục,practice|luyện tập,champion|nhà vô địch,medal|huy chương,prize|giải thưởng,record|kỷ lục,hobby|sở thích,dance|nhảy/múa,sing|hát,read|đọc sách,draw|vẽ,paint|tô màu,travel|du lịch,cook|nấu ăn,garden|làm vườn,fish|câu cá,camp|cắm trại,hike|đi bộ đường dài,photo|chụp ảnh,collect|sưu tầm,chess|cờ vua,puzzle|câu đố,movie|phim,concert|buổi hòa nhạc`,
// 11: Animals
`animal|động vật,dog|chó,cat|mèo,bird|chim,fish|cá,cow|bò,pig|lợn,horse|ngựa,sheep|cừu,goat|dê,chicken|gà,duck|vịt,rabbit|thỏ,mouse|chuột,snake|rắn,frog|ếch,monkey|khỉ,elephant|voi,lion|sư tử,tiger|hổ,bear|gấu,deer|hươu,wolf|sói,fox|cáo,whale|cá voi,shark|cá mập,dolphin|cá heo,turtle|rùa,insect|côn trùng,bee|ong,fly|ruồi,ant|kiến,spider|nhện,butterfly|bướm,pet|thú cưng,wild|hoang dã,zoo|sở thú,farm|nông trại,tree|cây,flower|hoa,grass|cỏ,leaf|lá,forest|rừng,river|sông,lake|hồ,sea|biển,ocean|đại dương,island|đảo,plant|cây/trồng,seed|hạt giống,rock|đá,sand|cát`,
// 12: Clothes
`shirt|áo sơ mi,t-shirt|áo phông,pants|quần dài,jeans|quần bò,shorts|quần ngắn,skirt|váy,dress|đầm,suit|bộ vest,jacket|áo khoác,coat|áo choàng,sweater|áo len,uniform|đồng phục,hat|mũ,cap|mũ lưỡi trai,scarf|khăn quàng,glove|găng tay,sock|tất,shoe|giày,boot|ủng,sandal|dép,slipper|dép lê,belt|thắt lưng,tie|cà vạt,button|nút/cúc,pocket|túi áo,wear|mặc,put on|mặc vào,take off|cởi ra,try on|thử đồ,fit|vừa,tight|chật,loose|rộng,size|cỡ,small|nhỏ,medium|vừa,large|lớn,cotton|vải cotton,silk|lụa,leather|da,fashion|thời trang,style|phong cách,modern|hiện đại,beautiful|đẹp,handsome|đẹp trai,pretty|xinh đẹp,ugly|xấu,tall|cao,short|thấp,thin|gầy,fat|béo,hair|tóc,beard|râu`,
// 13: Numbers
`one|một,two|hai,three|ba,four|bốn,five|năm,six|sáu,seven|bảy,eight|tám,nine|chín,ten|mười,twenty|hai mươi,thirty|ba mươi,forty|bốn mươi,fifty|năm mươi,hundred|trăm,thousand|nghìn,million|triệu,first|thứ nhất,second|thứ hai,third|thứ ba,half|một nửa,zero|số không,number|số,count|đếm,add|cộng,minus|trừ,total|tổng,time|thời gian,hour|giờ,minute|phút,second|giây,day|ngày,week|tuần,month|tháng,year|năm,Monday|thứ Hai,Tuesday|thứ Ba,Wednesday|thứ Tư,Thursday|thứ Năm,Friday|thứ Sáu,Saturday|thứ Bảy,Sunday|Chủ nhật,January|tháng Một,February|tháng Hai,March|tháng Ba,April|tháng Tư,May|tháng Năm,June|tháng Sáu,date|ngày tháng,calendar|lịch,clock|đồng hồ,noon|buổi trưa`,
// 14: Colors
`red|đỏ,blue|xanh dương,green|xanh lá,yellow|vàng,white|trắng,black|đen,brown|nâu,pink|hồng,purple|tím,orange|cam,gray|xám,gold|vàng kim,silver|bạc,dark|tối,light|sáng,bright|sáng chói,color|màu sắc,colorful|nhiều màu,circle|hình tròn,square|hình vuông,triangle|hình tam giác,rectangle|hình chữ nhật,star|hình sao,line|đường thẳng,point|điểm,corner|góc,side|cạnh,round|tròn,flat|phẳng,straight|thẳng,curve|đường cong,shape|hình dạng,pattern|hoa văn,stripe|sọc,dot|chấm,top|đỉnh,bottom|đáy,middle|giữa,center|trung tâm,edge|cạnh/mép,long|dài,short|ngắn,wide|rộng,narrow|hẹp,thick|dày,thin|mỏng,deep|sâu,shallow|nông,high|cao,low|thấp,big|lớn,small|nhỏ`,
// 15: Feelings
`happy|vui,sad|buồn,angry|giận,afraid|sợ,tired|mệt,excited|hào hứng,bored|chán,nervous|lo lắng,surprised|ngạc nhiên,worried|lo lắng,lonely|cô đơn,shy|nhút nhát,proud|tự hào,jealous|ghen tị,kind|tốt bụng,mean|xấu tính,honest|trung thực,brave|dũng cảm,lazy|lười,hardworking|chăm chỉ,patient|kiên nhẫn,polite|lịch sự,rude|thô lỗ,friendly|thân thiện,funny|vui tính,serious|nghiêm túc,quiet|ít nói,loud|ồn ào,smart|thông minh,stupid|ngu ngốc,careful|cẩn thận,careless|bất cẩn,confident|tự tin,generous|hào phóng,selfish|ích kỷ,calm|bình tĩnh,crazy|điên,strange|lạ,normal|bình thường,special|đặc biệt,nice|tốt/dễ thương,terrible|tệ,wonderful|tuyệt vời,love|yêu,hate|ghét,like|thích,miss|nhớ,hope|hy vọng,wish|ước,believe|tin tưởng,feel|cảm thấy,cry|khóc,laugh|cười`,
// 16: City
`city|thành phố,town|thị trấn,village|làng,street|đường phố,road|con đường,park|công viên,bank|ngân hàng,hospital|bệnh viện,school|trường,church|nhà thờ,temple|chùa,museum|bảo tàng,theater|nhà hát,cinema|rạp chiếu phim,library|thư viện,post office|bưu điện,police station|đồn cảnh sát,fire station|trạm cứu hỏa,market|chợ,supermarket|siêu thị,restaurant|nhà hàng,cafe|quán cà phê,hotel|khách sạn,pharmacy|nhà thuốc,gas station|trạm xăng,airport|sân bay,train station|nhà ga,bus stop|trạm xe buýt,bridge|cầu,tower|tháp,square|quảng trường,corner|góc đường,building|tòa nhà,factory|nhà máy,office|văn phòng,stadium|sân vận động,gym|phòng tập,swimming pool|hồ bơi,playground|sân chơi,garden|vườn hoa,fountain|đài phun nước,statue|tượng,sign|biển hiệu,traffic light|đèn giao thông,crosswalk|vạch qua đường,sidewalk|vỉa hè,parking lot|bãi đậu xe,map|bản đồ,direction|hướng,downtown|trung tâm`,
// 17: Technology
`phone|điện thoại,computer|máy tính,laptop|máy tính xách tay,tablet|máy tính bảng,screen|màn hình,keyboard|bàn phím,mouse|chuột máy tính,internet|mạng internet,website|trang web,email|thư điện tử,message|tin nhắn,call|gọi điện,text|nhắn tin,photo|ảnh,video|video,camera|máy ảnh,TV|ti vi,radio|đài,battery|pin,charger|sạc,cable|dây cáp,plug|phích cắm,button|nút bấm,switch|công tắc,power|nguồn điện,turn on|bật,turn off|tắt,download|tải xuống,upload|tải lên,save|lưu,delete|xóa,copy|sao chép,paste|dán,search|tìm kiếm,click|nhấp chuột,type|gõ,print|in,scan|quét,send|gửi,receive|nhận,share|chia sẻ,connect|kết nối,password|mật khẩu,username|tên đăng nhập,app|ứng dụng,file|tệp tin,folder|thư mục,data|dữ liệu,online|trực tuyến,offline|ngoại tuyến,wifi|wifi`,
// 18: Common Verbs
`go|đi,come|đến,be|là/ở,have|có,do|làm,say|nói,get|lấy/được,make|làm/tạo,know|biết,think|nghĩ,take|lấy,see|thấy/nhìn,want|muốn,give|cho,use|dùng,find|tìm,tell|kể/bảo,ask|hỏi,try|thử,need|cần,feel|cảm thấy,become|trở thành,leave|rời đi,put|đặt/để,mean|có nghĩa,keep|giữ,let|để cho,begin|bắt đầu,seem|có vẻ,show|cho xem,hear|nghe,move|di chuyển,live|sống,happen|xảy ra,bring|mang đến,carry|mang/xách,hold|giữ/cầm,wait|đợi,spend|dành/tiêu,open|mở,close|đóng,pull|kéo,push|đẩy,break|vỡ/phá,build|xây,cut|cắt,fill|đổ đầy,hang|treo,pick|chọn/nhặt,set|đặt/thiết lập,change|thay đổi,follow|theo,start|bắt đầu,stop|dừng`,
// 19: Adjectives
`good|tốt,bad|xấu/tệ,big|lớn,small|nhỏ,new|mới,old|cũ,long|dài,short|ngắn,high|cao,low|thấp,fast|nhanh,slow|chậm,hard|khó/cứng,soft|mềm,hot|nóng,cold|lạnh,clean|sạch,dirty|bẩn,rich|giàu,poor|nghèo,right|đúng,wrong|sai,true|thật,false|giả,full|đầy,empty|trống,open|mở,close|đóng,safe|an toàn,dangerous|nguy hiểm,important|quan trọng,possible|có thể,impossible|không thể,different|khác nhau,same|giống nhau,best|tốt nhất,worst|tệ nhất,real|thật,main|chính,common|phổ biến,enough|đủ,sure|chắc chắn,only|chỉ/duy nhất,very|rất,really|thực sự,too|quá,also|cũng,just|chỉ/vừa,still|vẫn,already|đã/rồi,always|luôn luôn,never|không bao giờ,maybe|có lẽ`,
// 20: Du lịch & Khám phá (CAM)
`century|thế kỷ,transport|vận chuyển/giao thông,director|giám đốc,officer|sĩ quan/nhân viên,official|chính thức/quan chức,agent|đại lý/nhân viên,member|thành viên,crew|thủy thủ đoàn/phi hành đoàn,captain|thuyền trưởng/đội trưởng,tourism|du lịch,tourist|du khách,tour|chuyến tham quan,guide|hướng dẫn viên,island|đảo,port|cảng,yacht|du thuyền,helicopter|trực thăng,accommodation|chỗ ở,journey|hành trình,destination|điểm đến,explore|khám phá,adventure|phiêu lưu,excursion|chuyến tham quan ngắn,resort|khu nghỉ dưỡng,cruise|du thuyền lớn,landmark|địa danh,souvenir|quà lưu niệm,scenery|phong cảnh,heritage|di sản,ruin|tàn tích,mainland|đất liền,region|vùng/khu vực,local|địa phương,visitor|du khách,view|cảnh/tầm nhìn,facilities|cơ sở vật chất,event|sự kiện,activity|hoạt động,cycling|đạp xe,swimming|bơi lội,hiking|đi bộ đường dài,camping|cắm trại,fishing|câu cá,sailing|chèo thuyền,surfing|lướt sóng,diving|lặn,contact|liên hệ,reserve|đặt trước,brochure|tờ rơi quảng cáo,continent|lục địa,desert|sa mạc,ground|mặt đất,entrance|lối vào,path|con đường/lối đi,track|đường mòn/theo dõi,trail|đường mòn,bay|vịnh,lodge|nhà nghỉ,campsite|bãi cắm trại,tent|lều,shelter|nơi trú ẩn,castle|lâu đài,fortress|pháo đài,palace|cung điện,monument|đài tưởng niệm,architecture|kiến trúc,ancient|cổ đại,medieval|trung cổ,historic|lịch sử,historical|thuộc lịch sử,famous|nổi tiếng,renowned|nổi tiếng,original|nguyên bản/gốc,originally|ban đầu,arrival|sự đến nơi,holiday|kỳ nghỉ,outdoor|ngoài trời,interior|nội thất/bên trong,somewhere|đâu đó,booking|đặt chỗ,rental|cho thuê,fee|phí,membership|tư cách thành viên,club|câu lạc bộ,award|giải thưởng,competition|cuộc thi,exhibition|triển lãm,gallery|phòng trưng bày,film|phim`,
// 21: Khoa học & Môi trường (CAM)
`environment|môi trường,nature|thiên nhiên,species|loài,habitat|môi trường sống,vegetation|thảm thực vật,conservation|bảo tồn,protect|bảo vệ,wildlife|động vật hoang dã,predator|động vật ăn thịt,prey|con mồi,breeding|sinh sản,native|bản địa,giant|khổng lồ,cattle|gia súc,population|dân số/quần thể,tortoise|rùa cạn,dolphin|cá heo,climate|khí hậu,temperature|nhiệt độ,drought|hạn hán,flood|lũ lụt,pollution|ô nhiễm,carbon|carbon,fossil|hóa thạch,renewable|tái tạo được,solar|năng lượng mặt trời,recycle|tái chế,recycling|việc tái chế,waste|chất thải/lãng phí,emission|khí thải,global|toàn cầu,warming|nóng lên,ecosystem|hệ sinh thái,environmental|thuộc môi trường,endangered|có nguy cơ tuyệt chủng,extinct|tuyệt chủng,survive|sống sót,adapt|thích nghi,evolution|tiến hóa,genetic|di truyền,gene|gen,cell|tế bào,organism|sinh vật,destruction|sự tàn phá,disease|bệnh,mortality|tỷ lệ tử vong,sanitation|vệ sinh,flow|dòng chảy,terrain|địa hình,volcano|núi lửa,mineral|khoáng sản,scientific|khoa học`,
// 22: Xã hội & Kinh tế (CAM)
`society|xã hội,community|cộng đồng,council|hội đồng,government|chính phủ,public|công cộng,national|quốc gia,international|quốc tế,economy|nền kinh tế,economic|kinh tế,industry|công nghiệp,industrial|công nghiệp,revolution|cuộc cách mạng,development|sự phát triển,growth|sự tăng trưởng,trade|thương mại,export|xuất khẩu,import|nhập khẩu,investment|đầu tư,profit|lợi nhuận,income|thu nhập,budget|ngân sách,poverty|nghèo đói,wealth|sự giàu có,wealthy|giàu có,opportunity|cơ hội,employment|việc làm,unemployment|thất nghiệp,employer|người sử dụng lao động,skill|kỹ năng,training|đào tạo,education|giáo dục,policy|chính sách,reform|cải cách,impact|tác động,influence|ảnh hưởng,survey|khảo sát,statistics|thống kê,percentage|phần trăm,increase|tăng,decrease|giảm,decline|suy giảm,significant|đáng kể,majority|đa số,minority|thiểu số,citizen|công dân,immigrant|người nhập cư,cultural|văn hóa,tradition|truyền thống,traditional|truyền thống,modern|hiện đại,progress|tiến bộ,challenge|thách thức,solution|giải pháp,crisis|khủng hoảng,conflict|xung đột,agreement|thỏa thuận,cooperation|hợp tác,crime|tội phạm,theft|trộm cắp,charity|từ thiện,volunteer|tình nguyện viên,contribution|đóng góp,demand|nhu cầu,labour|lao động,agriculture|nông nghiệp,manufacturing|sản xuất,production|sản xuất,commercial|thương mại,domestic|trong nước,expansion|mở rộng,social|xã hội,regional|khu vực,war|chiến tranh,payment|thanh toán,scheme|kế hoạch/đề án`,
// 23: Học thuật & Nghiên cứu (CAM)
`intelligence|trí thông minh,theory|lý thuyết,implicit|ngầm/ẩn,explicit|rõ ràng,cognitive|nhận thức,psychology|tâm lý học,behavior|hành vi,mental|tinh thần,ability|khả năng,capable|có khả năng,potential|tiềm năng,intelligent|thông minh,identify|nhận dạng,recognize|nhận ra,comprehend|hiểu,interpret|giải thích,evaluate|đánh giá,assess|đánh giá,assessment|sự đánh giá,compare|so sánh,contrast|tương phản,similar|tương tự,identical|giống hệt,unique|độc đáo,factor|yếu tố,aspect|khía cạnh,perspective|góc nhìn,approach|cách tiếp cận,concept|khái niệm,principle|nguyên tắc,assume|giả định,hypothesis|giả thuyết,phenomenon|hiện tượng,significant|có ý nghĩa,relevant|liên quan,context|bối cảnh,reference|tham khảo,source|nguồn,indicate|chỉ ra,demonstrate|chứng minh,suggest|gợi ý,argue|lập luận,claim|tuyên bố,support|ủng hộ,contradict|mâu thuẫn,conclude|kết luận,summary|tóm tắt,abstract|tóm tắt/trừu tượng,define|định nghĩa,category|thể loại,complex|phức tạp,fundamental|cơ bản,essential|cần thiết,primary|chính/sơ cấp,secondary|phụ/thứ cấp,research|nghiên cứu,experiment|thí nghiệm,laboratory|phòng thí nghiệm,observe|quan sát,discover|khám phá,evidence|bằng chứng,data|dữ liệu,analysis|phân tích,conclusion|kết luận,result|kết quả,process|quá trình,method|phương pháp,sample|mẫu,measure|đo lường,accurate|chính xác,precise|chính xác,reliable|đáng tin cậy`,
// 24: Công nghiệp & Vật liệu (CAM)
`glass|thủy tinh,stone|đá,copper|đồng,steel|thép,iron|sắt,metal|kim loại,wood|gỗ,concrete|bê tông,brick|gạch,cement|xi măng,material|vật liệu,substance|chất,chemical|hóa chất,liquid|chất lỏng,solid|chất rắn,gas|khí,fuel|nhiên liệu,oil|dầu,coal|than,energy|năng lượng,power|điện/sức mạnh,engine|động cơ,motor|động cơ,machine|máy móc,factory|nhà máy,manufacture|sản xuất,produce|sản xuất,product|sản phẩm,design|thiết kế,designer|nhà thiết kế,construction|xây dựng,structure|cấu trúc,foundation|nền móng,layer|lớp,surface|bề mặt,pipe|ống,wire|dây,tool|dụng cụ,device|thiết bị,equipment|thiết bị,melt|nấu chảy,heat|nung nóng,cool|làm nguội,shape|tạo hình,mold|khuôn,cast|đúc,drill|khoan,weld|hàn,polish|đánh bóng,assemble|lắp ráp,repair|sửa chữa,maintain|bảo trì,inspect|kiểm tra,quality|chất lượng,standard|tiêu chuẩn,raw|thô/nguyên liệu,cargo|hàng hóa,painting|bức tranh/sơn,restoration|sự phục hồi,restore|phục hồi,invention|phát minh`,
// 25: Kỹ năng & Giao tiếp (CAM)
`provide|cung cấp,organize|tổ chức,arrange|sắp xếp,continue|tiếp tục,allow|cho phép,prevent|ngăn chặn,avoid|tránh,encourage|khuyến khích,focus|tập trung,improve|cải thiện,gain|đạt được,achieve|đạt được,determine|xác định,explain|giải thích,describe|mô tả,discuss|thảo luận,separate|tách biệt,involve|liên quan/bao gồm,operate|vận hành,function|chức năng,select|chọn lọc,locate|xác định vị trí,predict|dự đoán,prepare|chuẩn bị,replace|thay thế,remove|loại bỏ,propose|đề xuất,declare|tuyên bố,ensure|đảm bảo,employ|tuyển dụng/sử dụng,serve|phục vụ,benefit|lợi ích,advantage|lợi thế,value|giá trị,limit|giới hạn,range|phạm vi,amount|số lượng,rate|tỷ lệ,level|mức độ,condition|điều kiện,opportunity|cơ hội,purpose|mục đích,reason|lý do,solution|giải pháp,problem|vấn đề,safety|an toàn,personal|cá nhân,individual|cá nhân/riêng,general|chung/tổng quát,basic|cơ bản,specific|cụ thể,recent|gần đây,recently|gần đây,particularly|đặc biệt,especially|đặc biệt là,directly|trực tiếp,clearly|rõ ràng,quickly|nhanh chóng,slightly|hơi/một chút,relatively|tương đối,fully|hoàn toàn,highly|rất/cao,equally|bằng nhau,apparently|rõ ràng là`,
// 26: Sức khỏe & Đời sống (CAM)
`fitness|thể lực/sức khỏe,improvement|sự cải thiện,leisure|giải trí/thời gian rảnh,supervisor|người giám sát,trainer|huấn luyện viên,professor|giáo sư,birth|sự sinh ra,infant|trẻ sơ sinh,human|con người,harm|gây hại,suffer|chịu đựng,recover|hồi phục,treat|điều trị,recommend|khuyến nghị,sufficient|đủ,necessary|cần thiết,suitable|phù hợp,available|có sẵn,useful|hữu ích,interested|quan tâm,interesting|thú vị,pleasant|dễ chịu,pleased|hài lòng,excellent|xuất sắc,lovely|đáng yêu,unusual|bất thường,widespread|lan rộng,ambitious|tham vọng,huge|khổng lồ,popular|phổ biến,double|gấp đôi,whole|toàn bộ,major|lớn/quan trọng,effective|hiệu quả,successful|thành công,likely|có khả năng,elite|tinh hoa,peak|đỉnh cao,concern|lo ngại,term|thuật ngữ/kỳ hạn,role|vai trò,trust|tin tưởng,damage|thiệt hại,deal|thỏa thuận/giải quyết,importance|tầm quan trọng,wonder|thắc mắc/kỳ diệu,notice|chú ý/thông báo,content|nội dung/hài lòng,sense|giác quan/ý nghĩa`,
// 27: Lịch sử & Khảo cổ (CAM)
`archaeological|khảo cổ học,dramatic|kịch tính,era|kỷ nguyên,significance|ý nghĩa/tầm quan trọng,access|sự tiếp cận,commission|ủy ban,land|đất đai,settler|người định cư,establishment|sự thành lập,programme|chương trình,extent|mức độ,report|báo cáo,volume|khối lượng/tập sách,period|giai đoạn,cycle|chu kỳ,application|ứng dụng/đơn xin,operation|hoạt động,position|vị trí,location|địa điểm,state|trạng thái/bang,system|hệ thống,technique|kỹ thuật,technology|công nghệ,queen|nữ hoàng,king|vua,hall|hội trường,carved|được chạm khắc,decorative|trang trí,sculpture|tác phẩm điêu khắc,rise|sự trỗi dậy/tăng,sudden|đột ngột,length|chiều dài,absence|sự vắng mặt,distinct|khác biệt,unprecedented|chưa từng có,barren|cằn cỗi,uneven|không đều`,
// 28: Giao thông & Đô thị (CAM 17) - London Underground, Amphitheatres/Stadiums, Skyscrapers, Education/Wealth
`underground|tàu điện ngầm,railway|đường sắt,locomotive|đầu máy xe lửa,carriage|toa tàu,tunnel|đường hầm,excavate|đào/khai quật,congested|tắc nghẽn,congestion|sự tắc nghẽn,astonishing|đáng kinh ngạc,advocate|ủng hộ/người ủng hộ,solicitor|luật sư (Anh),petition|kiến nghị/thỉnh nguyện,relocate|di dời,suburb|ngoại ô,suburban|ngoại ô,coincide|trùng hợp,parliament|quốc hội,legislation|luật pháp,municipal|thuộc thành phố,ventilation|sự thông gió,oversee|giám sát,prominent|nổi bật,skeptical|hoài nghi,locomotive|đầu máy,terminate|kết thúc/chấm dứt,deteriorate|xuống cấp,innovative|sáng tạo,excessive|quá mức,commuter|người đi làm hàng ngày,fare|tiền vé,route|tuyến đường,extension|mở rộng,inaugurate|khánh thành,critic|nhà phê bình,criticism|sự phê bình,propose|đề xuất,proposal|đề xuất,approve|phê duyệt,reject|từ chối,amphitheatre|đấu trường/nhà hát vòng tròn,arena|đấu trường,gladiator|đấu sĩ,spectator|khán giả,venue|địa điểm tổ chức,renovation|sự cải tạo,preservation|sự bảo tồn,versatile|đa năng,imposing|uy nghi/đồ sộ,monumental|hoành tráng,skyline|đường chân trời,skyscraper|tòa nhà chọc trời,demolish|phá dỡ,demolition|sự phá dỡ,storey|tầng (nhà),elevator|thang máy,steel-framed|khung thép,zoning|phân vùng,density|mật độ,plot|mảnh đất,landlord|chủ nhà,tenant|người thuê nhà,lease|hợp đồng thuê,inventory|bản kiểm kê,guild|phường hội,literacy|biết chữ,numerate|biết tính toán,arithmetic|số học,numeracy|khả năng tính toán,prosperity|sự thịnh vượng,prosperous|thịnh vượng,parish|giáo xứ/xã,estate|bất động sản/điền trang,accumulate|tích lũy,inheritance|sự thừa kế`,
// 29: Khoa học & Tự nhiên (CAM 17) - Dead Sea Scrolls, Thylacine, Tomatoes, Bats, Forests, Honey Bees
`scroll|cuộn giấy/cuộn sách,manuscript|bản thảo,parchment|da thuộc viết,fragment|mảnh vỡ,inscription|dòng chữ khắc,decipher|giải mã,antiquity|thời cổ đại,scholar|học giả,repository|kho lưu trữ,preserve|bảo quản,decay|phân hủy/suy tàn,cave|hang động,jar|bình/lọ,seal|con dấu/niêm phong,authentic|xác thực,forgery|đồ giả mạo,carbon dating|xác định niên đại carbon,thylacine|hổ Tasmania,marsupial|thú có túi,carnivore|động vật ăn thịt,nocturnal|hoạt động về đêm,pouch|túi (thú),stripe|sọc vằn,sighting|lần nhìn thấy,bounty|tiền thưởng,exterminate|tiêu diệt,persecution|sự đàn áp/bức hại,specimen|mẫu vật,captivity|sự nuôi nhốt,domestication|sự thuần hóa,cultivate|trồng trọt/canh tác,cultivation|sự canh tác,crop|mùa vụ/cây trồng,harvest|thu hoạch,yield|sản lượng,trait|đặc điểm,breed|giống/lai tạo,hybrid|lai,genome|bộ gen,mutation|đột biến,selective|chọn lọc,ancestor|tổ tiên,descendant|hậu duệ,bat|con dơi,echolocation|định vị bằng tiếng vang,insectivore|động vật ăn côn trùng,pollination|sự thụ phấn,pollinator|sinh vật thụ phấn,pest|sâu bệnh,pesticide|thuốc trừ sâu,canopy|tán rừng,undergrowth|bụi rậm dưới tán cây,deforestation|phá rừng,reforestation|trồng rừng lại,timber|gỗ xẻ,lumber|gỗ xây dựng,prescribed burn|đốt có kiểm soát,wildfire|cháy rừng,suppression|sự dập tắt,undergrowth|cây bụi dưới tán,ecosystem services|dịch vụ hệ sinh thái,waggle dance|điệu nhảy lắc (ong),honeybee|ong mật,hive|tổ ong,colony|đàn/thuộc địa,nectar|mật hoa,pollen|phấn hoa,forage|kiếm ăn,navigate|định hướng/điều hướng,orientation|sự định hướng,recruit|tuyển dụng/thu hút,communicate|giao tiếp,signal|tín hiệu,distance|khoảng cách,direction|hướng,migration|sự di cư,migratory|di cư`,
// 30: Nông nghiệp & Đô thị xanh (CAM 18) - Urban Farming, Forest Management, Green Roofs, Growth Mindset, Mixed-ability
`aeroponic|khí canh,hydroponic|thủy canh,soil-free|không dùng đất,irrigation|tưới tiêu,nutrient|chất dinh dưỡng,vertical farming|nông nghiệp thẳng đứng,greenhouse|nhà kính,seedling|cây con,transplant|cấy/ghép,fertilizer|phân bón,organic|hữu cơ,sustainable|bền vững,sustainability|sự bền vững,intensive|thâm canh,conventional|truyền thống,arable|có thể canh tác,fallow|đất bỏ hoang,rotation|luân canh,monoculture|độc canh,biodiversity|đa dạng sinh học,abundance|sự dồi dào,abundant|dồi dào,scarcity|sự khan hiếm,shortage|sự thiếu hụt,surplus|thặng dư,distribution|phân phối,consumption|tiêu thụ,renewable|tái tạo,degradation|sự suy thoái,erosion|sự xói mòn,runoff|nước chảy tràn,stormwater|nước mưa,retention|sự giữ lại,drainage|hệ thống thoát nước,substrate|lớp nền/giá thể,insulation|cách nhiệt,thermal|nhiệt,membrane|màng,waterproof|chống nước,rooftop|mái nhà,vegetation|thảm thực vật,habitat|môi trường sống,urban wildlife|động vật hoang dã đô thị,natural capital|vốn tự nhiên,mitigation|sự giảm nhẹ,mitigate|giảm nhẹ,adaptation|sự thích nghi,resilience|khả năng phục hồi,resilient|kiên cường,prescribed fire|đốt có kiểm soát,undergrowth|cây bụi dưới tán,canopy|tán cây,watershed|lưu vực,timber|gỗ xẻ,logging|khai thác gỗ,ecosystem|hệ sinh thái,forestry|lâm nghiệp,regeneration|sự tái sinh,old-growth|rừng già,density|mật độ,habitat loss|mất môi trường sống,mindset|tư duy/lối suy nghĩ,growth mindset|tư duy phát triển,fixed mindset|tư duy cố định,innate|bẩm sinh,inherent|vốn có/cố hữu,nurture|nuôi dưỡng,praise|khen ngợi,effort|nỗ lực,persistence|sự kiên trì,setback|trở ngại,struggle|đấu tranh,achievement|thành tựu,attainment|sự đạt được,streamed|phân loại theo năng lực,mixed-ability|đa trình độ,curriculum|chương trình giảng dạy,pedagogy|phương pháp sư phạm,differentiation|sự phân hóa,inclusive|bao trùm/hòa nhập,equity|sự công bằng,outcome|kết quả,underperform|kém hiệu quả,gifted|có năng khiếu,remedial|bổ trợ/sửa chữa`,
// 31: Công nghệ & Khám phá (CAM 18) - Space Junk, Stonehenge, AI, Building Materials, Steam Car, Continental Drift
`debris|mảnh vụn,orbit|quỹ đạo,satellite|vệ tinh,spacecraft|tàu vũ trụ,collision|va chạm,fragment|mảnh vỡ,trajectory|quỹ đạo bay,altitude|độ cao,velocity|vận tốc,propulsion|lực đẩy,decommission|ngừng hoạt động,junk|rác/phế liệu,hazard|mối nguy hiểm,catastrophic|thảm khốc,cascade|hiệu ứng dây chuyền,track|theo dõi,monitor|giám sát,radar|ra-đa,laser|tia laser,retrieve|thu hồi,Stonehenge|Stonehenge (di tích đá),megalith|cự thạch,monument|đài tưởng niệm,alignment|sự sắp xếp thẳng hàng,solstice|ngày hạ chí/đông chí,prehistoric|tiền sử,Neolithic|thời kỳ đồ đá mới,excavation|cuộc khai quật,ritual|nghi lễ,ceremonial|nghi lễ,burial|chôn cất,cremation|hỏa táng,sarsen|đá sarsen,bluestone|đá xanh,quarry|mỏ đá,transport|vận chuyển,erect|dựng lên,artificial intelligence|trí tuệ nhân tạo,algorithm|thuật toán,automation|tự động hóa,autonomous|tự trị,neural network|mạng thần kinh,machine learning|học máy,deep learning|học sâu,bias|thiên kiến,ethical|đạo đức,transparency|sự minh bạch,accountability|trách nhiệm giải trình,surveillance|giám sát,privacy|quyền riêng tư,regulation|quy định,workforce|lực lượng lao động,displacement|sự thay thế,augment|tăng cường,complement|bổ sung,timber|gỗ,bamboo|tre,hemp|cây gai dầu,cross-laminated|dán chéo lớp,composite|vật liệu tổng hợp,carbon footprint|dấu chân carbon,embodied energy|năng lượng hàm chứa,emission|khí thải,load-bearing|chịu lực,tensile strength|cường độ kéo,compression|nén,durability|độ bền,fireproof|chống cháy,insulate|cách nhiệt,sustainable material|vật liệu bền vững,steam engine|động cơ hơi nước,combustion|sự đốt cháy,piston|pít-tông,boiler|nồi hơi,horsepower|mã lực,gasoline|xăng,exhaust|khí thải,acceleration|gia tốc,velocity|vận tốc,aerodynamic|khí động học,rival|đối thủ,continental drift|trôi dạt lục địa,tectonic|kiến tạo,plate|mảng (địa chất),crust|vỏ (Trái Đất),mantle|lớp phủ (Trái Đất),magma|magma/dung nham,rift|khe nứt,expedition|cuộc thám hiểm,glacier|sông băng,geological|địa chất,erosion|xói mòn,sediment|trầm tích,stratum|tầng địa chất,paleontology|cổ sinh vật học,hypothesis|giả thuyết,skepticism|sự hoài nghi,controversy|tranh cãi,vindicate|minh oan/chứng minh đúng,paradigm shift|sự thay đổi mô hình`
];

// Parse raw data into structured vocabulary
const VOCAB_DATA = RAW.map((raw, i) => {
  const words = raw.split(',').map(entry => {
    const [word, meaning] = entry.split('|');
    return { word: word.trim(), meaning: meaning.trim() };
  });
  return { ...TOPIC_META[i], words };
});
